# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Teste File Filter package

on:
  push:
    branches: [ "main", "v3" ]
  pull_request:
    branches: [ "main" ]
  
jobs:

  run-tests:
  
    strategy:
      fail-fast: false
      matrix:
        package-name: ["File\ Filter"]     
        st-version: [4]
        os: ["ubuntu-latest", "macOS-latest", "windows-latest"]
        
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v4
      - uses: SublimeText/UnitTesting/actions/setup@v1
        with:
          package-name: "${{ matrix.package-name }}"
          sublime-text-version: ${{ matrix.st-version }}
      - uses: SublimeText/UnitTesting/actions/run-tests@v1
        with:
          coverage: true
          package-name: "${{ matrix.package-name }}"
      - uses: codecov/codecov-action@v4
